### ISSUE TITLE
Waterdrop's Performance Advantage? 

### ISSUE THREAD

**Issue by katpadi** [karafka/waterdrop#156]
Hello! Came by to ask the advantages of this Kafka client compared to the others. I'm looking for a performant producer which I can't achieve in my current producer client unfortunately. 

Some of my questions:
- do you have some performance metrics to easily compare at a glance? 
- what was your main motivation for this gem? How is it different from the others? 
- what was the best producer throughput that you have ever achieved?
- why did you shift to rdkafka?

Thanks in advance.

**Comment by mensfeld** [comment]
> do you have some performance metrics to easily compare at a glance?

Unfortunately no. We did extensive benchmarking before we wrote Waterdrop 2.0 to make sure, it performs the same or better than 1.4 (which is ruby-kafka driven) and my our standards, it performs much better.

> what was your main motivation for this gem? How is it different from the others?

- Concurrency support
- Stability
- Lack of issues with network glitches (buffer overflows)
- Support for more granular control of the production process (sync & async)

> what was the best producer throughput that you have ever achieved?

Please specify conditions - you mean per instance of a producer, per process or within a cluster?

> why did you shift to rdkafka?

I was tired of patching ruby-kafka ;) rdkafka is well supported C driver that has a huge community, thus it gets much more attention (due to bindings in many languages) than the pure ruby driver. It is also design to provide warranties that I expected and has a huge potential to be expanded with new functionalities.

We produce and consume tens of thousands of events per second and from time to time due to network glitches (or other issues) waterdrop with ruby-kafka would have buffer overflows and other problems. It also lacked more granular control of the way you can dispatch messages. Thus the decision.

We're running the `rc1` for several months now and we did not see any problems so far (I released final today).
