### ISSUE TITLE
What happens to buffer when not flushed?

### ISSUE THREAD

**Issue by katpadi** [karafka/waterdrop#193]
Is there a configuration that we could set up for the internal buffer to be flushed when a certain time is reached? Will the buffer respect the `linger.ms` configuration? What is the recommendation for handling this?

**Comment by mensfeld** [comment]
Hey @katpadi are we talking about WateDrop `2.0` or `1.4`?

**Comment by mensfeld** [comment]
I will assume you're on `2.0` for now and please correct me in case I was mistaken:

There are two buffers in WaterDrop. One in WaterDrop itself and the other in rdkafka. You are referring to `queue.buffering.max.ms`, thus I will assume that is of your interest.

> Is there a configuration that we could set up for the internal buffer to be flushed when a certain time is reached?

Yes and no. This would require a background thread or some sort of checking (for example during producing of other messages) for WaterDrop internal buffer. However:

> Will the buffer respect the `linger.ms` configuration? What is the recommendation for handling this?

`queue.buffering.max.ms` can be set. Then you need to skip using the WaterDrop internal buffer by using `produce_async` instead of using `buffer` with `flush_sync`.

Just to clarify the reasoning on WaterDrop having two "buffers". The WaterDrop one is being used by me to build accumulators that accumulate data with granular control. For example when I want to dispatch messages only when I got the message of my interest (for example for a lifecycle set of events), thus I am buffering until I explicitly want to flush. The rdkafka buffer (https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) ain't "context aware" thus can be used as a general buffer.

**Comment by mensfeld** [comment]
@katpadi I updated the readme accordingly to match your question. Feel free to followup with questions or to close if you're satisfied with the answer and the updated readme.

**Comment by katpadi** [comment]
@mensfeld  thanks for answering and yes I am talking about `2.0`. 

I saw your readme update and if it's OK, I want to verify that I understood it correctly.

It seems that:

1. Ideally, the use of WateDrop's `buffer` is to have control on **_WHEN_** you really want to flush the messages to Kafka. For async producer, it is normally  just based on `queue.buffering.max.ms` (and `batch.size` but it's not available yet for WaterDrop, right? https://github.com/karafka/waterdrop/issues/189)
2. From the readme update, it seems that  `queue.buffering.max.ms` can work with the internal `buffer` implementation. Does this mean that I can also opt to `flush` whenever I want to and still feel confident that no messages will be left out even if somewhere in the transaction, there's an error that prevented the code to `flush` explicitly?
3. So, WD's buffer is another buffer before the actual Kafka internal buffer which has its own limits i.e. kbytes, number of messages, etc? 

Thanks a lot for answering.

**Comment by mensfeld** [comment]
1. Yes, batch size is not yet available as referenced.
2. If we're talking about running the `#flush_sync` (notice that `#flash`is private) then if you run it, WaterDrop will wait until all messages are delivered to Kafka (not rdkafka), thus receiving 100% warranty that they were dispatched and sent to at least 1 broker (ack levels kick in here depending on your settings). In case only part of the messages would be delivered, an exception will be raised with delivery details.
3. Yes. It is a more high-level concept for business logic-aware operating.

In general if you need super-duper strong warranties on delivery rather than callbacks and notifications upon failures and you need to react on that in an unstable environment, go with WD buffers + sync flushing.

Also sidenote: I've been sending billions of messages via WD 2.0 and on some debug occasions I verified the "quality" of delivery. Not a single message was lost. However keep in mind, that there are when working with any types of buffers corner cases like process shutdown when you need to call `#close` to make sure all the things are flushed, etc. I did implement some safe guards (https://github.com/karafka/waterdrop/blob/master/lib/water_drop/producer.rb#L79) to make sure that despite not closing the producer if there are messages in the buffer, they are flushed.

**Comment by mensfeld** [comment]
One more thing: if you go with `'queue.buffering.max.ms'` bigger than 5 seconds, please remember to tune the `max_wait_timeout` waterdrop setting as if the buffer flushing frequency exceeds the `max_wait_timeout` you may get delivery failure errors

**Comment by katpadi** [comment]
I see. Thanks for the tips @mensfeld.

Another question, have you benchmarked `produce_sync` vs. `buffer` + `flush`? I'm basically just looking for some baseline. I will do my own benchmarking. Just curious if there are some available data that I can compare with.

**Comment by mensfeld** [comment]
Let me quote the author of rdkafka:

> Sync producing is generally a bad idea since it has poor performance (bound by rtt)

On top of that the sync in WD has to check the rdkafka delivery status from the handler every `wait_timeout` thus in theory if you would set it to 1 second and would have almost instant delivery, anyhow it would cost you 1 second. Ofc its default is 5ms but it is still a LOT of time if done one by one.

It is different with buffers (that's one of many reasons why WD has them) as you check many, thus within the time boundary you dispatch many effectively (per message) decreasing the cost.

The more you decrease the `wait_timeout` the more CPU it costs to check it.

I did benchmarks while ago and I have no idea why I did not include them in the repo 0_o It's probably me forgetting so if you end up with decent results please share and will be happy to include. Based on my poor memory, as always it depends.

If you buffer and flush big batches (lets say 100+) it will be several times or (even more) faster than using sync producing. There should not be much difference in between `#produce_async` vs `buffer` and `flush_async` as they are similar but just suited for different cases.

**Comment by mensfeld** [comment]
If you're satisfied with my answers please don't forget to :star:  the main karafka repo :) https://github.com/karafka/karafka - it helps me spread Karafka and WD awareness.

**Comment by katpadi** [comment]
Makes sense.

Will star the main repo, ofc.

Thanks a lot.

I'm just trying out different approaches as the transactions that I'm expecting are not entirely consistent. Events could be produced just once or 3 or sometimes 5 to 6 or more per transaction. Transactions are like a wave or sometimes just droplets lol. They are basically random. Thus, my initial gut says buffering would be sufficient in my use case. However, `produce_async` is also a good candidate I just can't verify the performance yet. And also, I would need to do callbacks and stuff to counter the lack of "ack" in the async producer.

Anyway, you've been very helpful and thanks again!

**Comment by mensfeld** [comment]
Based on your explanations I would go with a buffer and a sync flush with default `max_wait`. This should satisfy your needs. Good luck and do not hesitate to ping me in case of any questions.

**Comment by katpadi** [comment]
Hey @mensfeld! It seems like auto-flushing using the rdkafka `queue.buffering.max.ms` does not have an effect when using WD's `buffer` method. The buffer just gets filled but it never gets flushed based on the time. Not sure if you need more context from me but I just basically did the example from the readme.

**Comment by mensfeld** [comment]
@katpadi I think I phrased myself wrong. What I meant with the WD buffer is that you need to flush it manually but then anyhow the rdkafka buffer `queue.buffering.max.ms` may kick in as a second stage. WD buffer is not meant to be time based.

**Comment by katpadi** [comment]
@mensfeld - Gah! Sorry.

I also phrased my question wrong - I meant, auto-flushing does not happen. I buffered many times (without flushing) but `queue.buffering.max.ms` did not kick in. Is there a special configuration for this? I followed the readme and the only difference is that I left `queue.buffering.max.ms` as 5 (default) and I was expecting that I will never get to achieve the potential of `buffer` because `queue.buffering.max.ms` is too quick (just for testing purposes).

**Comment by mensfeld** [comment]
Ok, so we are NOT talking about WD buffer that does not have autoflushing but about rdkafka buffer, that is you followed this example right?

It does not happen because I messed up the readme :facepalm: can you try with the updated one? Sooooo sorry.

With just rdkafka buffers you're not suppose to use `#buffer` but `#produce_async` that will put it on the rdkafka queue.

I fixed the readme :face_with_head_bandage:

**Comment by mensfeld** [comment]
@katpadi did it help?
